# Generated by Django 5.2.7 on 2025-10-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='NombreCategria',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='precio',
            new_name='Precio',
        ),
    ]
