# Generated by Django 5.2.7 on 2025-11-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_nombrecategria_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='CantidadActual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='StockMinimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
