# Generated by Django 5.2.7 on 2025-11-10 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
