# Generated by Django 5.2.7 on 2025-11-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_carritoitem_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
